---
abstract: 'A generic OAuth2 Provider'
author:
  - 'Lenz Gschwendtner <lenz@springtimesoft.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OAuth2-Provider
requires:
  Any::Moose: 0
  Data::UUID: 0
  perl: 5.012
resources:
  repository: git://github.com/ideegeo/OAuth2-Provider.git
version: 0.1
